version: '2'
services:
  dockerapp:
    extends:
      file: common.yml
      service: dockerapp
    build: .
    ports:
      - "5000:5000"
  redis:
    extends:
      file: common.yml
      service: redis
